export * from './Header';
export * from './Home';
export * from './ButtonCustom';
export * from './About';
export * from "./Title"
export * from "./Carrossel"
export * from './Footer';
export * from "./PhotoPage"
export * from "./AcademyCard"